### ISSUE TITLE
rqworker fails while processing results  - no scan results are processed, no results are displayed in UI

### ISSUE THREAD

**Issue by dpolpa** [opsdisk/scantron#12]
Ubuntu 22.04

While processing scan results rqworker@1.service. fails with the traceback below
The console  UI  results page  gives  404
results from console/scan_results/complete are not moved to processed 

```
Jun 28 08:55:19 scantron-console python3[23962]: 08:55:19 Worker rq:worker:6af35bbc61d64062a5d9dface4ee9f81: started, version 1.9.0
Jun 28 08:55:19 scantron-console python3[23962]: 08:55:19 Subscribing to channel rq:pubsub:6af35bbc61d64062a5d9dface4ee9f81
Jun 28 08:55:19 scantron-console python3[23962]: 08:55:19 *** Listening on default...
Jun 28 08:55:19 scantron-console python3[23962]: 08:55:19 Cleaning registries for queue: default
Jun 28 09:04:56 scantron-console python3[23962]: 09:04:56 default: utility.process_scan_status_change({'id': 11, 'site_name': 'My Linode', 'start_time': date>
Jun 28 09:04:56 scantron-console python3[24290]: 09:04:56 Traceback (most recent call last):
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/worker.py", line 1031, in perform_job
Jun 28 09:04:56 scantron-console python3[24290]:     rv = job.perform()
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/job.py", line 749, in perform
Jun 28 09:04:56 scantron-console python3[24290]:     self._result = self._execute()
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/job.py", line 772, in _execute
Jun 28 09:04:56 scantron-console python3[24290]:     result = self.func(*self.args, **self.kwargs)
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/job.py", line 225, in func
Jun 28 09:04:56 scantron-console python3[24290]:     return import_attribute(self.func_name)
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/utils.py", line 158, in import_attribute
Jun 28 09:04:56 scantron-console python3[24290]:     attribute_owner = getattr(module, attribute_owner_name)
Jun 28 09:04:56 scantron-console python3[24290]: AttributeError: module 'utility' has no attribute ''
Jun 28 09:04:56 scantron-console python3[24290]: Traceback (most recent call last):
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/worker.py", line 1031, in perform_job
Jun 28 09:04:56 scantron-console python3[24290]:     rv = job.perform()
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/job.py", line 749, in perform
Jun 28 09:04:56 scantron-console python3[24290]:     self._result = self._execute()
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/job.py", line 772, in _execute
Jun 28 09:04:56 scantron-console python3[24290]:     result = self.func(*self.args, **self.kwargs)
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/job.py", line 225, in func
Jun 28 09:04:56 scantron-console python3[24290]:     return import_attribute(self.func_name)
Jun 28 09:04:56 scantron-console python3[24290]:   File "/home/scantron/console/.venv/lib/python3.8/site-packages/rq/utils.py", line 158, in import_attribute
Jun 28 09:04:56 scantron-console python3[24290]:     attribute_owner = getattr(module, attribute_owner_name)
Jun 28 09:04:56 scantron-console python3[24290]: AttributeError: module 'utility' has no attribute ''
```

**Comment by dpolpa** [comment]
SOLVED

The problem is a result of 2 packages having the same name 
`/home/scantron/console/.venv/lib/python3.8/site-packages/utility`
and 
`/home/scantron/console/utility.py`

The quick fix is to rename the file  `/home/scantron/console/utility.py` and all references to it in the code
namely in `/home/scantron/console/django_scantron/api/views.py`
